# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whopsaas.models.api_companies_id_get200_response import ApiCompaniesIdGet200Response

class TestApiCompaniesIdGet200Response(unittest.TestCase):
    """ApiCompaniesIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiCompaniesIdGet200Response:
        """Test ApiCompaniesIdGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiCompaniesIdGet200Response`
        """
        model = ApiCompaniesIdGet200Response()
        if include_optional:
            return ApiCompaniesIdGet200Response(
                id = 'biz_abc123',
                type = 'platform',
                status = 'active',
                title = '',
                email = '',
                slug = 'my-saas-company',
                logo_url = '',
                website_url = '',
                description = '',
                platform_fee_percent = 5.0,
                payout_minimum_amount = 50.0,
                payout_frequency = 'daily',
                stripe_account_id = '',
                stripe_onboarded = True,
                metadata = whopsaas.models.metadata.metadata(),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                count = whopsaas.models.company__count.Company__count(
                    products = 56, 
                    memberships = 56, 
                    payments = 56, 
                    users = 56, ),
                user_role = ''
            )
        else:
            return ApiCompaniesIdGet200Response(
        )
        """

    def testApiCompaniesIdGet200Response(self):
        """Test ApiCompaniesIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
