# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whopsaas.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_api_webhooks_get(self) -> None:
        """Test case for api_webhooks_get

        List webhooks
        """
        pass

    def test_api_webhooks_id_delete(self) -> None:
        """Test case for api_webhooks_id_delete

        Delete webhook
        """
        pass

    def test_api_webhooks_id_get(self) -> None:
        """Test case for api_webhooks_id_get

        Get webhook
        """
        pass

    def test_api_webhooks_id_put(self) -> None:
        """Test case for api_webhooks_id_put

        Update webhook
        """
        pass

    def test_api_webhooks_post(self) -> None:
        """Test case for api_webhooks_post

        Create webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
