# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whopsaas.models.company_create import CompanyCreate

class TestCompanyCreate(unittest.TestCase):
    """CompanyCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompanyCreate:
        """Test CompanyCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompanyCreate`
        """
        model = CompanyCreate()
        if include_optional:
            return CompanyCreate(
                title = '0',
                email = '',
                type = 'sub_merchant',
                logo_url = '',
                website_url = '',
                description = '',
                platform_fee_percent = 1.337,
                payout_minimum_amount = 1.337,
                payout_frequency = 'weekly',
                metadata = None
            )
        else:
            return CompanyCreate(
                title = '0',
                email = '',
        )
        """

    def testCompanyCreate(self):
        """Test CompanyCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
