# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whopsaas.models.api_webhooks_get200_response import ApiWebhooksGet200Response

class TestApiWebhooksGet200Response(unittest.TestCase):
    """ApiWebhooksGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiWebhooksGet200Response:
        """Test ApiWebhooksGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiWebhooksGet200Response`
        """
        model = ApiWebhooksGet200Response()
        if include_optional:
            return ApiWebhooksGet200Response(
                webhooks = [
                    whopsaas.models.webhook.Webhook(
                        id = 'whk_abc123', 
                        company_id = '', 
                        url = '', 
                        events = [
                            'payment.succeeded'
                            ], 
                        api_version = 'v1', 
                        secret = 'whsec_abc123...', 
                        active = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        _count = whopsaas.models.webhook__count.Webhook__count(
                            deliveries = 56, ), )
                    ],
                pagination = whopsaas.models.pagination.Pagination(
                    total = 56, 
                    limit = 56, 
                    offset = 56, 
                    has_more = True, )
            )
        else:
            return ApiWebhooksGet200Response(
        )
        """

    def testApiWebhooksGet200Response(self):
        """Test ApiWebhooksGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
