# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whopsaas.api.products_api import ProductsApi


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductsApi()

    def tearDown(self) -> None:
        pass

    def test_api_products_get(self) -> None:
        """Test case for api_products_get

        List products
        """
        pass

    def test_api_products_id_delete(self) -> None:
        """Test case for api_products_id_delete

        Delete product
        """
        pass

    def test_api_products_id_get(self) -> None:
        """Test case for api_products_id_get

        Get product
        """
        pass

    def test_api_products_id_put(self) -> None:
        """Test case for api_products_id_put

        Update product
        """
        pass

    def test_api_products_post(self) -> None:
        """Test case for api_products_post

        Create product
        """
        pass


if __name__ == '__main__':
    unittest.main()
