# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whopsaas.models.api_products_get200_response import ApiProductsGet200Response

class TestApiProductsGet200Response(unittest.TestCase):
    """ApiProductsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiProductsGet200Response:
        """Test ApiProductsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiProductsGet200Response`
        """
        model = ApiProductsGet200Response()
        if include_optional:
            return ApiProductsGet200Response(
                products = [
                    whopsaas.models.product.Product(
                        id = 'prod_abc123', 
                        company_id = 'biz_xyz789', 
                        title = 'Pro Plan', 
                        description = 'Premium features with priority support', 
                        image_url = '', 
                        price_amount = 49.99, 
                        price_minor_units = 4999, 
                        currency = 'USD', 
                        plan_type = 'one_time', 
                        billing_period = 56, 
                        trial_days = 14, 
                        active = True, 
                        metadata = whopsaas.models.metadata.metadata(), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = whopsaas.models.pagination.Pagination(
                    total = 56, 
                    limit = 56, 
                    offset = 56, 
                    has_more = True, )
            )
        else:
            return ApiProductsGet200Response(
        )
        """

    def testApiProductsGet200Response(self):
        """Test ApiProductsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
