ignoredBuiltDependencies:
  - '@nestjs/core'

onlyBuiltDependencies:
  - '@openapitools/openapi-generator-cli'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
