/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiCompaniesGet200Response,
  ApiCompaniesIdGet200Response,
  Company,
  CompanyCreate,
  CompanyUpdate,
} from '../models/index';
import {
    ApiCompaniesGet200ResponseFromJSON,
    ApiCompaniesGet200ResponseToJSON,
    ApiCompaniesIdGet200ResponseFromJSON,
    ApiCompaniesIdGet200ResponseToJSON,
    CompanyFromJSON,
    CompanyToJSON,
    CompanyCreateFromJSON,
    CompanyCreateToJSON,
    CompanyUpdateFromJSON,
    CompanyUpdateToJSON,
} from '../models/index';

export interface ApiCompaniesGetRequest {
    role?: ApiCompaniesGetRoleEnum;
    type?: ApiCompaniesGetTypeEnum;
    limit?: number;
    offset?: number;
}

export interface ApiCompaniesIdGetRequest {
    id: string;
}

export interface ApiCompaniesIdPutRequest {
    id: string;
    companyUpdate: CompanyUpdate;
}

export interface ApiCompaniesPostRequest {
    companyCreate: CompanyCreate;
}

/**
 * 
 */
export class CompaniesApi extends runtime.BaseAPI {

    /**
     * List all companies user has access to
     * List companies
     */
    async apiCompaniesGetRaw(requestParameters: ApiCompaniesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiCompaniesGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/companies`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiCompaniesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List all companies user has access to
     * List companies
     */
    async apiCompaniesGet(requestParameters: ApiCompaniesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiCompaniesGet200Response> {
        const response = await this.apiCompaniesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get company
     */
    async apiCompaniesIdGetRaw(requestParameters: ApiCompaniesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiCompaniesIdGet200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCompaniesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/companies/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiCompaniesIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get company
     */
    async apiCompaniesIdGet(requestParameters: ApiCompaniesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiCompaniesIdGet200Response> {
        const response = await this.apiCompaniesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update company (requires admin/owner role)
     * Update company
     */
    async apiCompaniesIdPutRaw(requestParameters: ApiCompaniesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Company>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCompaniesIdPut().'
            );
        }

        if (requestParameters['companyUpdate'] == null) {
            throw new runtime.RequiredError(
                'companyUpdate',
                'Required parameter "companyUpdate" was null or undefined when calling apiCompaniesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/companies/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CompanyUpdateToJSON(requestParameters['companyUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanyFromJSON(jsonValue));
    }

    /**
     * Update company (requires admin/owner role)
     * Update company
     */
    async apiCompaniesIdPut(requestParameters: ApiCompaniesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Company> {
        const response = await this.apiCompaniesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new company (user becomes owner)
     * Create company
     */
    async apiCompaniesPostRaw(requestParameters: ApiCompaniesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Company>> {
        if (requestParameters['companyCreate'] == null) {
            throw new runtime.RequiredError(
                'companyCreate',
                'Required parameter "companyCreate" was null or undefined when calling apiCompaniesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/companies`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CompanyCreateToJSON(requestParameters['companyCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanyFromJSON(jsonValue));
    }

    /**
     * Create a new company (user becomes owner)
     * Create company
     */
    async apiCompaniesPost(requestParameters: ApiCompaniesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Company> {
        const response = await this.apiCompaniesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiCompaniesGetRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member'
} as const;
export type ApiCompaniesGetRoleEnum = typeof ApiCompaniesGetRoleEnum[keyof typeof ApiCompaniesGetRoleEnum];
/**
 * @export
 */
export const ApiCompaniesGetTypeEnum = {
    Platform: 'platform',
    SubMerchant: 'sub_merchant'
} as const;
export type ApiCompaniesGetTypeEnum = typeof ApiCompaniesGetTypeEnum[keyof typeof ApiCompaniesGetTypeEnum];
