/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiMembershipsGet200Response,
  Membership,
  MembershipUpdate,
} from '../models/index';
import {
    ApiMembershipsGet200ResponseFromJSON,
    ApiMembershipsGet200ResponseToJSON,
    MembershipFromJSON,
    MembershipToJSON,
    MembershipUpdateFromJSON,
    MembershipUpdateToJSON,
} from '../models/index';

export interface ApiMembershipsGetRequest {
    companyId?: string;
    userId?: string;
    productId?: string;
    status?: ApiMembershipsGetStatusEnum;
    limit?: number;
    offset?: number;
}

export interface ApiMembershipsIdGetRequest {
    id: string;
}

export interface ApiMembershipsIdPutRequest {
    id: string;
    membershipUpdate: MembershipUpdate;
}

/**
 * 
 */
export class MembershipsApi extends runtime.BaseAPI {

    /**
     * List memberships (scoped by company_id or user)
     * List memberships
     */
    async apiMembershipsGetRaw(requestParameters: ApiMembershipsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiMembershipsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/memberships`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiMembershipsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List memberships (scoped by company_id or user)
     * List memberships
     */
    async apiMembershipsGet(requestParameters: ApiMembershipsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiMembershipsGet200Response> {
        const response = await this.apiMembershipsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get membership
     */
    async apiMembershipsIdGetRaw(requestParameters: ApiMembershipsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Membership>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMembershipsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/memberships/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MembershipFromJSON(jsonValue));
    }

    /**
     * Get membership
     */
    async apiMembershipsIdGet(requestParameters: ApiMembershipsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Membership> {
        const response = await this.apiMembershipsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update membership status or metadata
     * Update membership
     */
    async apiMembershipsIdPutRaw(requestParameters: ApiMembershipsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Membership>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMembershipsIdPut().'
            );
        }

        if (requestParameters['membershipUpdate'] == null) {
            throw new runtime.RequiredError(
                'membershipUpdate',
                'Required parameter "membershipUpdate" was null or undefined when calling apiMembershipsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/memberships/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MembershipUpdateToJSON(requestParameters['membershipUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MembershipFromJSON(jsonValue));
    }

    /**
     * Update membership status or metadata
     * Update membership
     */
    async apiMembershipsIdPut(requestParameters: ApiMembershipsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Membership> {
        const response = await this.apiMembershipsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiMembershipsGetStatusEnum = {
    Active: 'active',
    PastDue: 'past_due',
    Canceled: 'canceled',
    Expired: 'expired',
    Trialing: 'trialing'
} as const;
export type ApiMembershipsGetStatusEnum = typeof ApiMembershipsGetStatusEnum[keyof typeof ApiMembershipsGetStatusEnum];
