/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiProductsGet200Response,
  ApiProductsIdDelete200Response,
  Product,
  ProductCreate,
  ProductUpdate,
} from '../models/index';
import {
    ApiProductsGet200ResponseFromJSON,
    ApiProductsGet200ResponseToJSON,
    ApiProductsIdDelete200ResponseFromJSON,
    ApiProductsIdDelete200ResponseToJSON,
    ProductFromJSON,
    ProductToJSON,
    ProductCreateFromJSON,
    ProductCreateToJSON,
    ProductUpdateFromJSON,
    ProductUpdateToJSON,
} from '../models/index';

export interface ApiProductsGetRequest {
    companyId: string;
    active?: boolean;
    limit?: number;
    offset?: number;
}

export interface ApiProductsIdDeleteRequest {
    id: string;
}

export interface ApiProductsIdGetRequest {
    id: string;
}

export interface ApiProductsIdPutRequest {
    id: string;
    productUpdate: ProductUpdate;
}

export interface ApiProductsPostRequest {
    productCreate: ProductCreate;
}

/**
 * 
 */
export class ProductsApi extends runtime.BaseAPI {

    /**
     * List all products for a company with pagination
     * List products
     */
    async apiProductsGetRaw(requestParameters: ApiProductsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiProductsGet200Response>> {
        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling apiProductsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/products`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiProductsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List all products for a company with pagination
     * List products
     */
    async apiProductsGet(requestParameters: ApiProductsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiProductsGet200Response> {
        const response = await this.apiProductsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft delete (sets active=false). Only owners can delete. Prevents deletion if active memberships exist.
     * Delete product
     */
    async apiProductsIdDeleteRaw(requestParameters: ApiProductsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiProductsIdDelete200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProductsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/products/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiProductsIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * Soft delete (sets active=false). Only owners can delete. Prevents deletion if active memberships exist.
     * Delete product
     */
    async apiProductsIdDelete(requestParameters: ApiProductsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiProductsIdDelete200Response> {
        const response = await this.apiProductsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get product
     */
    async apiProductsIdGetRaw(requestParameters: ApiProductsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProductsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/products/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Get product
     */
    async apiProductsIdGet(requestParameters: ApiProductsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.apiProductsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update product (requires admin/owner role)
     * Update product
     */
    async apiProductsIdPutRaw(requestParameters: ApiProductsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProductsIdPut().'
            );
        }

        if (requestParameters['productUpdate'] == null) {
            throw new runtime.RequiredError(
                'productUpdate',
                'Required parameter "productUpdate" was null or undefined when calling apiProductsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/products/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProductUpdateToJSON(requestParameters['productUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Update product (requires admin/owner role)
     * Update product
     */
    async apiProductsIdPut(requestParameters: ApiProductsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.apiProductsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new product (requires admin/owner role)
     * Create product
     */
    async apiProductsPostRaw(requestParameters: ApiProductsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        if (requestParameters['productCreate'] == null) {
            throw new runtime.RequiredError(
                'productCreate',
                'Required parameter "productCreate" was null or undefined when calling apiProductsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/products`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProductCreateToJSON(requestParameters['productCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Create a new product (requires admin/owner role)
     * Create product
     */
    async apiProductsPost(requestParameters: ApiProductsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.apiProductsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
