/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiWebhooksGet200Response,
  ApiWebhooksIdDelete200Response,
  ApiWebhooksPost201Response,
  Webhook,
  WebhookCreate,
  WebhookUpdate,
} from '../models/index';
import {
    ApiWebhooksGet200ResponseFromJSON,
    ApiWebhooksGet200ResponseToJSON,
    ApiWebhooksIdDelete200ResponseFromJSON,
    ApiWebhooksIdDelete200ResponseToJSON,
    ApiWebhooksPost201ResponseFromJSON,
    ApiWebhooksPost201ResponseToJSON,
    WebhookFromJSON,
    WebhookToJSON,
    WebhookCreateFromJSON,
    WebhookCreateToJSON,
    WebhookUpdateFromJSON,
    WebhookUpdateToJSON,
} from '../models/index';

export interface ApiWebhooksGetRequest {
    companyId: string;
    active?: boolean;
    limit?: number;
    offset?: number;
}

export interface ApiWebhooksIdDeleteRequest {
    id: string;
}

export interface ApiWebhooksIdGetRequest {
    id: string;
}

export interface ApiWebhooksIdPutRequest {
    id: string;
    webhookUpdate: WebhookUpdate;
}

export interface ApiWebhooksPostRequest {
    webhookCreate: WebhookCreate;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * List webhook subscriptions (admins only)
     * List webhooks
     */
    async apiWebhooksGetRaw(requestParameters: ApiWebhooksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiWebhooksGet200Response>> {
        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling apiWebhooksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['companyId'] != null) {
            queryParameters['company_id'] = requestParameters['companyId'];
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/webhooks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiWebhooksGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List webhook subscriptions (admins only)
     * List webhooks
     */
    async apiWebhooksGet(requestParameters: ApiWebhooksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiWebhooksGet200Response> {
        const response = await this.apiWebhooksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete webhook
     */
    async apiWebhooksIdDeleteRaw(requestParameters: ApiWebhooksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiWebhooksIdDelete200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiWebhooksIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiWebhooksIdDelete200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete webhook
     */
    async apiWebhooksIdDelete(requestParameters: ApiWebhooksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiWebhooksIdDelete200Response> {
        const response = await this.apiWebhooksIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get webhook
     */
    async apiWebhooksIdGetRaw(requestParameters: ApiWebhooksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webhook>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiWebhooksIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookFromJSON(jsonValue));
    }

    /**
     * Get webhook
     */
    async apiWebhooksIdGet(requestParameters: ApiWebhooksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webhook> {
        const response = await this.apiWebhooksIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update webhook
     */
    async apiWebhooksIdPutRaw(requestParameters: ApiWebhooksIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Webhook>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiWebhooksIdPut().'
            );
        }

        if (requestParameters['webhookUpdate'] == null) {
            throw new runtime.RequiredError(
                'webhookUpdate',
                'Required parameter "webhookUpdate" was null or undefined when calling apiWebhooksIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WebhookUpdateToJSON(requestParameters['webhookUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookFromJSON(jsonValue));
    }

    /**
     * Update webhook
     */
    async apiWebhooksIdPut(requestParameters: ApiWebhooksIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Webhook> {
        const response = await this.apiWebhooksIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create webhook subscription (admins only). Returns full secret only on creation.
     * Create webhook
     */
    async apiWebhooksPostRaw(requestParameters: ApiWebhooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiWebhooksPost201Response>> {
        if (requestParameters['webhookCreate'] == null) {
            throw new runtime.RequiredError(
                'webhookCreate',
                'Required parameter "webhookCreate" was null or undefined when calling apiWebhooksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/webhooks`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhookCreateToJSON(requestParameters['webhookCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiWebhooksPost201ResponseFromJSON(jsonValue));
    }

    /**
     * Create webhook subscription (admins only). Returns full secret only on creation.
     * Create webhook
     */
    async apiWebhooksPost(requestParameters: ApiWebhooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiWebhooksPost201Response> {
        const response = await this.apiWebhooksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
