# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from whopsaas.models.company_count import CompanyCount
from typing import Optional, Set
from typing_extensions import Self

class Company(BaseModel):
    """
    Company
    """ # noqa: E501
    id: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    slug: Optional[StrictStr] = None
    logo_url: Optional[StrictStr] = None
    website_url: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    platform_fee_percent: Optional[Union[StrictFloat, StrictInt]] = None
    payout_minimum_amount: Optional[Union[StrictFloat, StrictInt]] = None
    payout_frequency: Optional[StrictStr] = None
    stripe_account_id: Optional[StrictStr] = None
    stripe_onboarded: Optional[StrictBool] = None
    metadata: Optional[Dict[str, Any]] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    count: Optional[CompanyCount] = Field(default=None, alias="_count")
    __properties: ClassVar[List[str]] = ["id", "type", "status", "title", "email", "slug", "logo_url", "website_url", "description", "platform_fee_percent", "payout_minimum_amount", "payout_frequency", "stripe_account_id", "stripe_onboarded", "metadata", "created_at", "updated_at", "_count"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['platform', 'sub_merchant']):
            raise ValueError("must be one of enum values ('platform', 'sub_merchant')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'pending_kyc', 'suspended', 'closed']):
            raise ValueError("must be one of enum values ('active', 'pending_kyc', 'suspended', 'closed')")
        return value

    @field_validator('payout_frequency')
    def payout_frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['daily', 'weekly', 'monthly']):
            raise ValueError("must be one of enum values ('daily', 'weekly', 'monthly')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Company from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of count
        if self.count:
            _dict['_count'] = self.count.to_dict()
        # set to None if logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.logo_url is None and "logo_url" in self.model_fields_set:
            _dict['logo_url'] = None

        # set to None if website_url (nullable) is None
        # and model_fields_set contains the field
        if self.website_url is None and "website_url" in self.model_fields_set:
            _dict['website_url'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if stripe_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.stripe_account_id is None and "stripe_account_id" in self.model_fields_set:
            _dict['stripe_account_id'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Company from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "title": obj.get("title"),
            "email": obj.get("email"),
            "slug": obj.get("slug"),
            "logo_url": obj.get("logo_url"),
            "website_url": obj.get("website_url"),
            "description": obj.get("description"),
            "platform_fee_percent": obj.get("platform_fee_percent"),
            "payout_minimum_amount": obj.get("payout_minimum_amount"),
            "payout_frequency": obj.get("payout_frequency"),
            "stripe_account_id": obj.get("stripe_account_id"),
            "stripe_onboarded": obj.get("stripe_onboarded"),
            "metadata": obj.get("metadata"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "_count": CompanyCount.from_dict(obj["_count"]) if obj.get("_count") is not None else None
        })
        return _obj


