# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CompanyCreate(BaseModel):
    """
    CompanyCreate
    """ # noqa: E501
    title: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    email: StrictStr
    type: Optional[StrictStr] = 'sub_merchant'
    logo_url: Optional[StrictStr] = None
    website_url: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    platform_fee_percent: Optional[Union[StrictFloat, StrictInt]] = 5.0
    payout_minimum_amount: Optional[Union[StrictFloat, StrictInt]] = 50.0
    payout_frequency: Optional[StrictStr] = 'weekly'
    metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["title", "email", "type", "logo_url", "website_url", "description", "platform_fee_percent", "payout_minimum_amount", "payout_frequency", "metadata"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['platform', 'sub_merchant']):
            raise ValueError("must be one of enum values ('platform', 'sub_merchant')")
        return value

    @field_validator('payout_frequency')
    def payout_frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['daily', 'weekly', 'monthly']):
            raise ValueError("must be one of enum values ('daily', 'weekly', 'monthly')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompanyCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompanyCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "email": obj.get("email"),
            "type": obj.get("type") if obj.get("type") is not None else 'sub_merchant',
            "logo_url": obj.get("logo_url"),
            "website_url": obj.get("website_url"),
            "description": obj.get("description"),
            "platform_fee_percent": obj.get("platform_fee_percent") if obj.get("platform_fee_percent") is not None else 5.0,
            "payout_minimum_amount": obj.get("payout_minimum_amount") if obj.get("payout_minimum_amount") is not None else 50.0,
            "payout_frequency": obj.get("payout_frequency") if obj.get("payout_frequency") is not None else 'weekly',
            "metadata": obj.get("metadata")
        })
        return _obj


