# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from whopsaas.models.company import Company
from whopsaas.models.membership_user import MembershipUser
from whopsaas.models.product import Product
from typing import Optional, Set
from typing_extensions import Self

class Membership(BaseModel):
    """
    Membership
    """ # noqa: E501
    id: Optional[StrictStr] = None
    user_id: Optional[StrictStr] = None
    product_id: Optional[StrictStr] = None
    company_id: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    stripe_subscription_id: Optional[StrictStr] = None
    current_period_start: Optional[datetime] = None
    current_period_end: Optional[datetime] = None
    cancel_at: Optional[datetime] = None
    canceled_at: Optional[datetime] = None
    trial_end: Optional[datetime] = None
    metadata: Optional[Dict[str, Any]] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    user: Optional[MembershipUser] = None
    product: Optional[Product] = None
    company: Optional[Company] = None
    __properties: ClassVar[List[str]] = ["id", "user_id", "product_id", "company_id", "status", "stripe_subscription_id", "current_period_start", "current_period_end", "cancel_at", "canceled_at", "trial_end", "metadata", "created_at", "updated_at", "user", "product", "company"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'past_due', 'canceled', 'expired', 'trialing']):
            raise ValueError("must be one of enum values ('active', 'past_due', 'canceled', 'expired', 'trialing')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Membership from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of product
        if self.product:
            _dict['product'] = self.product.to_dict()
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['company'] = self.company.to_dict()
        # set to None if stripe_subscription_id (nullable) is None
        # and model_fields_set contains the field
        if self.stripe_subscription_id is None and "stripe_subscription_id" in self.model_fields_set:
            _dict['stripe_subscription_id'] = None

        # set to None if current_period_start (nullable) is None
        # and model_fields_set contains the field
        if self.current_period_start is None and "current_period_start" in self.model_fields_set:
            _dict['current_period_start'] = None

        # set to None if current_period_end (nullable) is None
        # and model_fields_set contains the field
        if self.current_period_end is None and "current_period_end" in self.model_fields_set:
            _dict['current_period_end'] = None

        # set to None if cancel_at (nullable) is None
        # and model_fields_set contains the field
        if self.cancel_at is None and "cancel_at" in self.model_fields_set:
            _dict['cancel_at'] = None

        # set to None if canceled_at (nullable) is None
        # and model_fields_set contains the field
        if self.canceled_at is None and "canceled_at" in self.model_fields_set:
            _dict['canceled_at'] = None

        # set to None if trial_end (nullable) is None
        # and model_fields_set contains the field
        if self.trial_end is None and "trial_end" in self.model_fields_set:
            _dict['trial_end'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Membership from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "user_id": obj.get("user_id"),
            "product_id": obj.get("product_id"),
            "company_id": obj.get("company_id"),
            "status": obj.get("status"),
            "stripe_subscription_id": obj.get("stripe_subscription_id"),
            "current_period_start": obj.get("current_period_start"),
            "current_period_end": obj.get("current_period_end"),
            "cancel_at": obj.get("cancel_at"),
            "canceled_at": obj.get("canceled_at"),
            "trial_end": obj.get("trial_end"),
            "metadata": obj.get("metadata"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "user": MembershipUser.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "product": Product.from_dict(obj["product"]) if obj.get("product") is not None else None,
            "company": Company.from_dict(obj["company"]) if obj.get("company") is not None else None
        })
        return _obj


