# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ProductCreate(BaseModel):
    """
    ProductCreate
    """ # noqa: E501
    company_id: StrictStr
    title: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    description: Optional[StrictStr] = None
    image_url: Optional[StrictStr] = None
    price_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Price in dollars (e.g., 49.99)")
    price_minor_units: Optional[StrictInt] = Field(default=None, description="Price in cents (e.g., 4999) - provide EITHER this OR price_amount")
    currency: Optional[StrictStr] = 'USD'
    plan_type: StrictStr
    billing_period: Optional[StrictInt] = None
    trial_days: Optional[StrictInt] = 0
    active: Optional[StrictBool] = True
    metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["company_id", "title", "description", "image_url", "price_amount", "price_minor_units", "currency", "plan_type", "billing_period", "trial_days", "active", "metadata"]

    @field_validator('plan_type')
    def plan_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['one_time', 'monthly', 'yearly']):
            raise ValueError("must be one of enum values ('one_time', 'monthly', 'yearly')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProductCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProductCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "company_id": obj.get("company_id"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "image_url": obj.get("image_url"),
            "price_amount": obj.get("price_amount"),
            "price_minor_units": obj.get("price_minor_units"),
            "currency": obj.get("currency") if obj.get("currency") is not None else 'USD',
            "plan_type": obj.get("plan_type"),
            "billing_period": obj.get("billing_period"),
            "trial_days": obj.get("trial_days") if obj.get("trial_days") is not None else 0,
            "active": obj.get("active") if obj.get("active") is not None else True,
            "metadata": obj.get("metadata")
        })
        return _obj


