# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class WebhookCreate(BaseModel):
    """
    WebhookCreate
    """ # noqa: E501
    company_id: StrictStr
    url: StrictStr
    events: Annotated[List[StrictStr], Field(min_length=1)]
    api_version: Optional[StrictStr] = 'v1'
    active: Optional[StrictBool] = True
    __properties: ClassVar[List[str]] = ["company_id", "url", "events", "api_version", "active"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "company_id": obj.get("company_id"),
            "url": obj.get("url"),
            "events": obj.get("events"),
            "api_version": obj.get("api_version") if obj.get("api_version") is not None else 'v1',
            "active": obj.get("active") if obj.get("active") is not None else True
        })
        return _obj


