# coding: utf-8

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from whopsaas.models.webhook_count import WebhookCount
from typing import Optional, Set
from typing_extensions import Self

class Webhook(BaseModel):
    """
    Webhook
    """ # noqa: E501
    id: Optional[StrictStr] = None
    company_id: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    events: Optional[List[StrictStr]] = None
    api_version: Optional[StrictStr] = 'v1'
    secret: Optional[StrictStr] = Field(default=None, description="HMAC secret (masked after creation)")
    active: Optional[StrictBool] = None
    created_at: Optional[datetime] = None
    count: Optional[WebhookCount] = Field(default=None, alias="_count")
    __properties: ClassVar[List[str]] = ["id", "company_id", "url", "events", "api_version", "secret", "active", "created_at", "_count"]

    @field_validator('events')
    def events_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['payment.succeeded', 'payment.failed', 'membership.created', 'membership.updated', 'membership.canceled', 'product.created', 'product.updated', 'product.deleted']):
                raise ValueError("each list item must be one of ('payment.succeeded', 'payment.failed', 'membership.created', 'membership.updated', 'membership.canceled', 'product.created', 'product.updated', 'product.deleted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Webhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of count
        if self.count:
            _dict['_count'] = self.count.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Webhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "company_id": obj.get("company_id"),
            "url": obj.get("url"),
            "events": obj.get("events"),
            "api_version": obj.get("api_version") if obj.get("api_version") is not None else 'v1',
            "secret": obj.get("secret"),
            "active": obj.get("active"),
            "created_at": obj.get("created_at"),
            "_count": WebhookCount.from_dict(obj["_count"]) if obj.get("_count") is not None else None
        })
        return _obj


