/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { ApiCompaniesGet200ResponseCompaniesInner } from './ApiCompaniesGet200ResponseCompaniesInner';
import {
    ApiCompaniesGet200ResponseCompaniesInnerFromJSON,
    ApiCompaniesGet200ResponseCompaniesInnerFromJSONTyped,
    ApiCompaniesGet200ResponseCompaniesInnerToJSON,
    ApiCompaniesGet200ResponseCompaniesInnerToJSONTyped,
} from './ApiCompaniesGet200ResponseCompaniesInner';

/**
 * 
 * @export
 * @interface ApiCompaniesGet200Response
 */
export interface ApiCompaniesGet200Response {
    /**
     * 
     * @type {Array<ApiCompaniesGet200ResponseCompaniesInner>}
     * @memberof ApiCompaniesGet200Response
     */
    companies?: Array<ApiCompaniesGet200ResponseCompaniesInner>;
    /**
     * 
     * @type {Pagination}
     * @memberof ApiCompaniesGet200Response
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ApiCompaniesGet200Response interface.
 */
export function instanceOfApiCompaniesGet200Response(value: object): value is ApiCompaniesGet200Response {
    return true;
}

export function ApiCompaniesGet200ResponseFromJSON(json: any): ApiCompaniesGet200Response {
    return ApiCompaniesGet200ResponseFromJSONTyped(json, false);
}

export function ApiCompaniesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCompaniesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'companies': json['companies'] == null ? undefined : ((json['companies'] as Array<any>).map(ApiCompaniesGet200ResponseCompaniesInnerFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ApiCompaniesGet200ResponseToJSON(json: any): ApiCompaniesGet200Response {
    return ApiCompaniesGet200ResponseToJSONTyped(json, false);
}

export function ApiCompaniesGet200ResponseToJSONTyped(value?: ApiCompaniesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companies': value['companies'] == null ? undefined : ((value['companies'] as Array<any>).map(ApiCompaniesGet200ResponseCompaniesInnerToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

