/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyCount } from './CompanyCount';
import {
    CompanyCountFromJSON,
    CompanyCountFromJSONTyped,
    CompanyCountToJSON,
    CompanyCountToJSONTyped,
} from './CompanyCount';

/**
 * 
 * @export
 * @interface ApiCompaniesIdGet200Response
 */
export interface ApiCompaniesIdGet200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    type?: ApiCompaniesIdGet200ResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    status?: ApiCompaniesIdGet200ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    websiteUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiCompaniesIdGet200Response
     */
    platformFeePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiCompaniesIdGet200Response
     */
    payoutMinimumAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    payoutFrequency?: ApiCompaniesIdGet200ResponsePayoutFrequencyEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    stripeAccountId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiCompaniesIdGet200Response
     */
    stripeOnboarded?: boolean;
    /**
     * 
     * @type {object}
     * @memberof ApiCompaniesIdGet200Response
     */
    metadata?: object | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiCompaniesIdGet200Response
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiCompaniesIdGet200Response
     */
    updatedAt?: Date;
    /**
     * 
     * @type {CompanyCount}
     * @memberof ApiCompaniesIdGet200Response
     */
    count?: CompanyCount;
    /**
     * 
     * @type {string}
     * @memberof ApiCompaniesIdGet200Response
     */
    userRole?: string;
}


/**
 * @export
 */
export const ApiCompaniesIdGet200ResponseTypeEnum = {
    Platform: 'platform',
    SubMerchant: 'sub_merchant'
} as const;
export type ApiCompaniesIdGet200ResponseTypeEnum = typeof ApiCompaniesIdGet200ResponseTypeEnum[keyof typeof ApiCompaniesIdGet200ResponseTypeEnum];

/**
 * @export
 */
export const ApiCompaniesIdGet200ResponseStatusEnum = {
    Active: 'active',
    PendingKyc: 'pending_kyc',
    Suspended: 'suspended',
    Closed: 'closed'
} as const;
export type ApiCompaniesIdGet200ResponseStatusEnum = typeof ApiCompaniesIdGet200ResponseStatusEnum[keyof typeof ApiCompaniesIdGet200ResponseStatusEnum];

/**
 * @export
 */
export const ApiCompaniesIdGet200ResponsePayoutFrequencyEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Monthly: 'monthly'
} as const;
export type ApiCompaniesIdGet200ResponsePayoutFrequencyEnum = typeof ApiCompaniesIdGet200ResponsePayoutFrequencyEnum[keyof typeof ApiCompaniesIdGet200ResponsePayoutFrequencyEnum];


/**
 * Check if a given object implements the ApiCompaniesIdGet200Response interface.
 */
export function instanceOfApiCompaniesIdGet200Response(value: object): value is ApiCompaniesIdGet200Response {
    return true;
}

export function ApiCompaniesIdGet200ResponseFromJSON(json: any): ApiCompaniesIdGet200Response {
    return ApiCompaniesIdGet200ResponseFromJSONTyped(json, false);
}

export function ApiCompaniesIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCompaniesIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'] == null ? undefined : json['title'],
        'email': json['email'] == null ? undefined : json['email'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'websiteUrl': json['website_url'] == null ? undefined : json['website_url'],
        'description': json['description'] == null ? undefined : json['description'],
        'platformFeePercent': json['platform_fee_percent'] == null ? undefined : json['platform_fee_percent'],
        'payoutMinimumAmount': json['payout_minimum_amount'] == null ? undefined : json['payout_minimum_amount'],
        'payoutFrequency': json['payout_frequency'] == null ? undefined : json['payout_frequency'],
        'stripeAccountId': json['stripe_account_id'] == null ? undefined : json['stripe_account_id'],
        'stripeOnboarded': json['stripe_onboarded'] == null ? undefined : json['stripe_onboarded'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'count': json['_count'] == null ? undefined : CompanyCountFromJSON(json['_count']),
        'userRole': json['user_role'] == null ? undefined : json['user_role'],
    };
}

export function ApiCompaniesIdGet200ResponseToJSON(json: any): ApiCompaniesIdGet200Response {
    return ApiCompaniesIdGet200ResponseToJSONTyped(json, false);
}

export function ApiCompaniesIdGet200ResponseToJSONTyped(value?: ApiCompaniesIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': value['status'],
        'title': value['title'],
        'email': value['email'],
        'slug': value['slug'],
        'logo_url': value['logoUrl'],
        'website_url': value['websiteUrl'],
        'description': value['description'],
        'platform_fee_percent': value['platformFeePercent'],
        'payout_minimum_amount': value['payoutMinimumAmount'],
        'payout_frequency': value['payoutFrequency'],
        'stripe_account_id': value['stripeAccountId'],
        'stripe_onboarded': value['stripeOnboarded'],
        'metadata': value['metadata'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        '_count': CompanyCountToJSON(value['count']),
        'user_role': value['userRole'],
    };
}

