/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Membership } from './Membership';
import {
    MembershipFromJSON,
    MembershipFromJSONTyped,
    MembershipToJSON,
    MembershipToJSONTyped,
} from './Membership';

/**
 * 
 * @export
 * @interface ApiMembershipsGet200Response
 */
export interface ApiMembershipsGet200Response {
    /**
     * 
     * @type {Array<Membership>}
     * @memberof ApiMembershipsGet200Response
     */
    memberships?: Array<Membership>;
    /**
     * 
     * @type {Pagination}
     * @memberof ApiMembershipsGet200Response
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ApiMembershipsGet200Response interface.
 */
export function instanceOfApiMembershipsGet200Response(value: object): value is ApiMembershipsGet200Response {
    return true;
}

export function ApiMembershipsGet200ResponseFromJSON(json: any): ApiMembershipsGet200Response {
    return ApiMembershipsGet200ResponseFromJSONTyped(json, false);
}

export function ApiMembershipsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMembershipsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'memberships': json['memberships'] == null ? undefined : ((json['memberships'] as Array<any>).map(MembershipFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ApiMembershipsGet200ResponseToJSON(json: any): ApiMembershipsGet200Response {
    return ApiMembershipsGet200ResponseToJSONTyped(json, false);
}

export function ApiMembershipsGet200ResponseToJSONTyped(value?: ApiMembershipsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberships': value['memberships'] == null ? undefined : ((value['memberships'] as Array<any>).map(MembershipToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

