/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface ApiProductsIdDelete200Response
 */
export interface ApiProductsIdDelete200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiProductsIdDelete200Response
     */
    message?: string;
    /**
     * 
     * @type {Product}
     * @memberof ApiProductsIdDelete200Response
     */
    product?: Product;
}

/**
 * Check if a given object implements the ApiProductsIdDelete200Response interface.
 */
export function instanceOfApiProductsIdDelete200Response(value: object): value is ApiProductsIdDelete200Response {
    return true;
}

export function ApiProductsIdDelete200ResponseFromJSON(json: any): ApiProductsIdDelete200Response {
    return ApiProductsIdDelete200ResponseFromJSONTyped(json, false);
}

export function ApiProductsIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiProductsIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
    };
}

export function ApiProductsIdDelete200ResponseToJSON(json: any): ApiProductsIdDelete200Response {
    return ApiProductsIdDelete200ResponseToJSONTyped(json, false);
}

export function ApiProductsIdDelete200ResponseToJSONTyped(value?: ApiProductsIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'product': ProductToJSON(value['product']),
    };
}

