/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface ApiProductsGet200Response
 */
export interface ApiProductsGet200Response {
    /**
     * 
     * @type {Array<Product>}
     * @memberof ApiProductsGet200Response
     */
    products?: Array<Product>;
    /**
     * 
     * @type {Pagination}
     * @memberof ApiProductsGet200Response
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ApiProductsGet200Response interface.
 */
export function instanceOfApiProductsGet200Response(value: object): value is ApiProductsGet200Response {
    return true;
}

export function ApiProductsGet200ResponseFromJSON(json: any): ApiProductsGet200Response {
    return ApiProductsGet200ResponseFromJSONTyped(json, false);
}

export function ApiProductsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiProductsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'products': json['products'] == null ? undefined : ((json['products'] as Array<any>).map(ProductFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ApiProductsGet200ResponseToJSON(json: any): ApiProductsGet200Response {
    return ApiProductsGet200ResponseToJSONTyped(json, false);
}

export function ApiProductsGet200ResponseToJSONTyped(value?: ApiProductsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'products': value['products'] == null ? undefined : ((value['products'] as Array<any>).map(ProductToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

