/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Webhook } from './Webhook';
import {
    WebhookFromJSON,
    WebhookFromJSONTyped,
    WebhookToJSON,
    WebhookToJSONTyped,
} from './Webhook';

/**
 * 
 * @export
 * @interface ApiWebhooksGet200Response
 */
export interface ApiWebhooksGet200Response {
    /**
     * 
     * @type {Array<Webhook>}
     * @memberof ApiWebhooksGet200Response
     */
    webhooks?: Array<Webhook>;
    /**
     * 
     * @type {Pagination}
     * @memberof ApiWebhooksGet200Response
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ApiWebhooksGet200Response interface.
 */
export function instanceOfApiWebhooksGet200Response(value: object): value is ApiWebhooksGet200Response {
    return true;
}

export function ApiWebhooksGet200ResponseFromJSON(json: any): ApiWebhooksGet200Response {
    return ApiWebhooksGet200ResponseFromJSONTyped(json, false);
}

export function ApiWebhooksGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWebhooksGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'webhooks': json['webhooks'] == null ? undefined : ((json['webhooks'] as Array<any>).map(WebhookFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ApiWebhooksGet200ResponseToJSON(json: any): ApiWebhooksGet200Response {
    return ApiWebhooksGet200ResponseToJSONTyped(json, false);
}

export function ApiWebhooksGet200ResponseToJSONTyped(value?: ApiWebhooksGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhooks': value['webhooks'] == null ? undefined : ((value['webhooks'] as Array<any>).map(WebhookToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

