/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiWebhooksIdDelete200Response
 */
export interface ApiWebhooksIdDelete200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiWebhooksIdDelete200Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiWebhooksIdDelete200Response
     */
    id?: string;
}

/**
 * Check if a given object implements the ApiWebhooksIdDelete200Response interface.
 */
export function instanceOfApiWebhooksIdDelete200Response(value: object): value is ApiWebhooksIdDelete200Response {
    return true;
}

export function ApiWebhooksIdDelete200ResponseFromJSON(json: any): ApiWebhooksIdDelete200Response {
    return ApiWebhooksIdDelete200ResponseFromJSONTyped(json, false);
}

export function ApiWebhooksIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWebhooksIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ApiWebhooksIdDelete200ResponseToJSON(json: any): ApiWebhooksIdDelete200Response {
    return ApiWebhooksIdDelete200ResponseToJSONTyped(json, false);
}

export function ApiWebhooksIdDelete200ResponseToJSONTyped(value?: ApiWebhooksIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'id': value['id'],
    };
}

