/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyUpdate
 */
export interface CompanyUpdate {
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdate
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdate
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdate
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdate
     */
    websiteUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CompanyUpdate
     */
    platformFeePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyUpdate
     */
    payoutMinimumAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyUpdate
     */
    payoutFrequency?: CompanyUpdatePayoutFrequencyEnum;
    /**
     * Only owners can change status
     * @type {string}
     * @memberof CompanyUpdate
     */
    status?: CompanyUpdateStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof CompanyUpdate
     */
    metadata?: object | null;
}


/**
 * @export
 */
export const CompanyUpdatePayoutFrequencyEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Monthly: 'monthly'
} as const;
export type CompanyUpdatePayoutFrequencyEnum = typeof CompanyUpdatePayoutFrequencyEnum[keyof typeof CompanyUpdatePayoutFrequencyEnum];

/**
 * @export
 */
export const CompanyUpdateStatusEnum = {
    Active: 'active',
    PendingKyc: 'pending_kyc',
    Suspended: 'suspended',
    Closed: 'closed'
} as const;
export type CompanyUpdateStatusEnum = typeof CompanyUpdateStatusEnum[keyof typeof CompanyUpdateStatusEnum];


/**
 * Check if a given object implements the CompanyUpdate interface.
 */
export function instanceOfCompanyUpdate(value: object): value is CompanyUpdate {
    return true;
}

export function CompanyUpdateFromJSON(json: any): CompanyUpdate {
    return CompanyUpdateFromJSONTyped(json, false);
}

export function CompanyUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'email': json['email'] == null ? undefined : json['email'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'websiteUrl': json['website_url'] == null ? undefined : json['website_url'],
        'description': json['description'] == null ? undefined : json['description'],
        'platformFeePercent': json['platform_fee_percent'] == null ? undefined : json['platform_fee_percent'],
        'payoutMinimumAmount': json['payout_minimum_amount'] == null ? undefined : json['payout_minimum_amount'],
        'payoutFrequency': json['payout_frequency'] == null ? undefined : json['payout_frequency'],
        'status': json['status'] == null ? undefined : json['status'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CompanyUpdateToJSON(json: any): CompanyUpdate {
    return CompanyUpdateToJSONTyped(json, false);
}

export function CompanyUpdateToJSONTyped(value?: CompanyUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'email': value['email'],
        'logo_url': value['logoUrl'],
        'website_url': value['websiteUrl'],
        'description': value['description'],
        'platform_fee_percent': value['platformFeePercent'],
        'payout_minimum_amount': value['payoutMinimumAmount'],
        'payout_frequency': value['payoutFrequency'],
        'status': value['status'],
        'metadata': value['metadata'],
    };
}

