/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyCreate
 */
export interface CompanyCreate {
    /**
     * 
     * @type {string}
     * @memberof CompanyCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyCreate
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyCreate
     */
    type?: CompanyCreateTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CompanyCreate
     */
    logoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyCreate
     */
    websiteUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyCreate
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyCreate
     */
    platformFeePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyCreate
     */
    payoutMinimumAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyCreate
     */
    payoutFrequency?: CompanyCreatePayoutFrequencyEnum;
    /**
     * 
     * @type {object}
     * @memberof CompanyCreate
     */
    metadata?: object;
}


/**
 * @export
 */
export const CompanyCreateTypeEnum = {
    Platform: 'platform',
    SubMerchant: 'sub_merchant'
} as const;
export type CompanyCreateTypeEnum = typeof CompanyCreateTypeEnum[keyof typeof CompanyCreateTypeEnum];

/**
 * @export
 */
export const CompanyCreatePayoutFrequencyEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Monthly: 'monthly'
} as const;
export type CompanyCreatePayoutFrequencyEnum = typeof CompanyCreatePayoutFrequencyEnum[keyof typeof CompanyCreatePayoutFrequencyEnum];


/**
 * Check if a given object implements the CompanyCreate interface.
 */
export function instanceOfCompanyCreate(value: object): value is CompanyCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CompanyCreateFromJSON(json: any): CompanyCreate {
    return CompanyCreateFromJSONTyped(json, false);
}

export function CompanyCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'email': json['email'],
        'type': json['type'] == null ? undefined : json['type'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'websiteUrl': json['website_url'] == null ? undefined : json['website_url'],
        'description': json['description'] == null ? undefined : json['description'],
        'platformFeePercent': json['platform_fee_percent'] == null ? undefined : json['platform_fee_percent'],
        'payoutMinimumAmount': json['payout_minimum_amount'] == null ? undefined : json['payout_minimum_amount'],
        'payoutFrequency': json['payout_frequency'] == null ? undefined : json['payout_frequency'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CompanyCreateToJSON(json: any): CompanyCreate {
    return CompanyCreateToJSONTyped(json, false);
}

export function CompanyCreateToJSONTyped(value?: CompanyCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'email': value['email'],
        'type': value['type'],
        'logo_url': value['logoUrl'],
        'website_url': value['websiteUrl'],
        'description': value['description'],
        'platform_fee_percent': value['platformFeePercent'],
        'payout_minimum_amount': value['payoutMinimumAmount'],
        'payout_frequency': value['payoutFrequency'],
        'metadata': value['metadata'],
    };
}

