/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyCount
 */
export interface CompanyCount {
    /**
     * 
     * @type {number}
     * @memberof CompanyCount
     */
    products?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyCount
     */
    memberships?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyCount
     */
    payments?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyCount
     */
    users?: number;
}

/**
 * Check if a given object implements the CompanyCount interface.
 */
export function instanceOfCompanyCount(value: object): value is CompanyCount {
    return true;
}

export function CompanyCountFromJSON(json: any): CompanyCount {
    return CompanyCountFromJSONTyped(json, false);
}

export function CompanyCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyCount {
    if (json == null) {
        return json;
    }
    return {
        
        'products': json['products'] == null ? undefined : json['products'],
        'memberships': json['memberships'] == null ? undefined : json['memberships'],
        'payments': json['payments'] == null ? undefined : json['payments'],
        'users': json['users'] == null ? undefined : json['users'],
    };
}

export function CompanyCountToJSON(json: any): CompanyCount {
    return CompanyCountToJSONTyped(json, false);
}

export function CompanyCountToJSONTyped(value?: CompanyCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'products': value['products'],
        'memberships': value['memberships'],
        'payments': value['payments'],
        'users': value['users'],
    };
}

