/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Company } from './Company';
import {
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
    CompanyToJSONTyped,
} from './Company';
import type { MembershipUser } from './MembershipUser';
import {
    MembershipUserFromJSON,
    MembershipUserFromJSONTyped,
    MembershipUserToJSON,
    MembershipUserToJSONTyped,
} from './MembershipUser';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface Membership
 */
export interface Membership {
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    companyId?: string;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    status?: MembershipStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    stripeSubscriptionId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    currentPeriodStart?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    currentPeriodEnd?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    cancelAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    canceledAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    trialEnd?: Date | null;
    /**
     * 
     * @type {object}
     * @memberof Membership
     */
    metadata?: object | null;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    updatedAt?: Date;
    /**
     * 
     * @type {MembershipUser}
     * @memberof Membership
     */
    user?: MembershipUser;
    /**
     * 
     * @type {Product}
     * @memberof Membership
     */
    product?: Product;
    /**
     * 
     * @type {Company}
     * @memberof Membership
     */
    company?: Company;
}


/**
 * @export
 */
export const MembershipStatusEnum = {
    Active: 'active',
    PastDue: 'past_due',
    Canceled: 'canceled',
    Expired: 'expired',
    Trialing: 'trialing'
} as const;
export type MembershipStatusEnum = typeof MembershipStatusEnum[keyof typeof MembershipStatusEnum];


/**
 * Check if a given object implements the Membership interface.
 */
export function instanceOfMembership(value: object): value is Membership {
    return true;
}

export function MembershipFromJSON(json: any): Membership {
    return MembershipFromJSONTyped(json, false);
}

export function MembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Membership {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'productId': json['product_id'] == null ? undefined : json['product_id'],
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'stripeSubscriptionId': json['stripe_subscription_id'] == null ? undefined : json['stripe_subscription_id'],
        'currentPeriodStart': json['current_period_start'] == null ? undefined : (new Date(json['current_period_start'])),
        'currentPeriodEnd': json['current_period_end'] == null ? undefined : (new Date(json['current_period_end'])),
        'cancelAt': json['cancel_at'] == null ? undefined : (new Date(json['cancel_at'])),
        'canceledAt': json['canceled_at'] == null ? undefined : (new Date(json['canceled_at'])),
        'trialEnd': json['trial_end'] == null ? undefined : (new Date(json['trial_end'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'user': json['user'] == null ? undefined : MembershipUserFromJSON(json['user']),
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
        'company': json['company'] == null ? undefined : CompanyFromJSON(json['company']),
    };
}

export function MembershipToJSON(json: any): Membership {
    return MembershipToJSONTyped(json, false);
}

export function MembershipToJSONTyped(value?: Membership | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'product_id': value['productId'],
        'company_id': value['companyId'],
        'status': value['status'],
        'stripe_subscription_id': value['stripeSubscriptionId'],
        'current_period_start': value['currentPeriodStart'] == null ? value['currentPeriodStart'] : value['currentPeriodStart'].toISOString(),
        'current_period_end': value['currentPeriodEnd'] == null ? value['currentPeriodEnd'] : value['currentPeriodEnd'].toISOString(),
        'cancel_at': value['cancelAt'] == null ? value['cancelAt'] : value['cancelAt'].toISOString(),
        'canceled_at': value['canceledAt'] == null ? value['canceledAt'] : value['canceledAt'].toISOString(),
        'trial_end': value['trialEnd'] == null ? value['trialEnd'] : value['trialEnd'].toISOString(),
        'metadata': value['metadata'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'user': MembershipUserToJSON(value['user']),
        'product': ProductToJSON(value['product']),
        'company': CompanyToJSON(value['company']),
    };
}

