/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MembershipUpdate
 */
export interface MembershipUpdate {
    /**
     * Only company admins can change status
     * @type {string}
     * @memberof MembershipUpdate
     */
    status?: MembershipUpdateStatusEnum;
    /**
     * Schedule cancellation (members can cancel own)
     * @type {Date}
     * @memberof MembershipUpdate
     */
    cancelAt?: Date | null;
    /**
     * Only company admins can update metadata
     * @type {object}
     * @memberof MembershipUpdate
     */
    metadata?: object | null;
}


/**
 * @export
 */
export const MembershipUpdateStatusEnum = {
    Active: 'active',
    PastDue: 'past_due',
    Canceled: 'canceled',
    Expired: 'expired',
    Trialing: 'trialing'
} as const;
export type MembershipUpdateStatusEnum = typeof MembershipUpdateStatusEnum[keyof typeof MembershipUpdateStatusEnum];


/**
 * Check if a given object implements the MembershipUpdate interface.
 */
export function instanceOfMembershipUpdate(value: object): value is MembershipUpdate {
    return true;
}

export function MembershipUpdateFromJSON(json: any): MembershipUpdate {
    return MembershipUpdateFromJSONTyped(json, false);
}

export function MembershipUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembershipUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'cancelAt': json['cancel_at'] == null ? undefined : (new Date(json['cancel_at'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function MembershipUpdateToJSON(json: any): MembershipUpdate {
    return MembershipUpdateToJSONTyped(json, false);
}

export function MembershipUpdateToJSONTyped(value?: MembershipUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'cancel_at': value['cancelAt'] == null ? value['cancelAt'] : value['cancelAt'].toISOString(),
        'metadata': value['metadata'],
    };
}

