/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MembershipUser
 */
export interface MembershipUser {
    /**
     * 
     * @type {string}
     * @memberof MembershipUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipUser
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipUser
     */
    avatarUrl?: string;
}

/**
 * Check if a given object implements the MembershipUser interface.
 */
export function instanceOfMembershipUser(value: object): value is MembershipUser {
    return true;
}

export function MembershipUserFromJSON(json: any): MembershipUser {
    return MembershipUserFromJSONTyped(json, false);
}

export function MembershipUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembershipUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
    };
}

export function MembershipUserToJSON(json: any): MembershipUser {
    return MembershipUserToJSONTyped(json, false);
}

export function MembershipUserToJSONTyped(value?: MembershipUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
        'avatar_url': value['avatarUrl'],
    };
}

