/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductUpdate
 */
export interface ProductUpdate {
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdate
     */
    priceAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdate
     */
    priceMinorUnits?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    planType?: ProductUpdatePlanTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdate
     */
    billingPeriod?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdate
     */
    trialDays?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductUpdate
     */
    active?: boolean;
    /**
     * 
     * @type {object}
     * @memberof ProductUpdate
     */
    metadata?: object | null;
}


/**
 * @export
 */
export const ProductUpdatePlanTypeEnum = {
    OneTime: 'one_time',
    Monthly: 'monthly',
    Yearly: 'yearly'
} as const;
export type ProductUpdatePlanTypeEnum = typeof ProductUpdatePlanTypeEnum[keyof typeof ProductUpdatePlanTypeEnum];


/**
 * Check if a given object implements the ProductUpdate interface.
 */
export function instanceOfProductUpdate(value: object): value is ProductUpdate {
    return true;
}

export function ProductUpdateFromJSON(json: any): ProductUpdate {
    return ProductUpdateFromJSONTyped(json, false);
}

export function ProductUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'priceAmount': json['price_amount'] == null ? undefined : json['price_amount'],
        'priceMinorUnits': json['price_minor_units'] == null ? undefined : json['price_minor_units'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'planType': json['plan_type'] == null ? undefined : json['plan_type'],
        'billingPeriod': json['billing_period'] == null ? undefined : json['billing_period'],
        'trialDays': json['trial_days'] == null ? undefined : json['trial_days'],
        'active': json['active'] == null ? undefined : json['active'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ProductUpdateToJSON(json: any): ProductUpdate {
    return ProductUpdateToJSONTyped(json, false);
}

export function ProductUpdateToJSONTyped(value?: ProductUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'image_url': value['imageUrl'],
        'price_amount': value['priceAmount'],
        'price_minor_units': value['priceMinorUnits'],
        'currency': value['currency'],
        'plan_type': value['planType'],
        'billing_period': value['billingPeriod'],
        'trial_days': value['trialDays'],
        'active': value['active'],
        'metadata': value['metadata'],
    };
}

