/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductCreate
 */
export interface ProductCreate {
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    imageUrl?: string;
    /**
     * Price in dollars (e.g., 49.99)
     * @type {number}
     * @memberof ProductCreate
     */
    priceAmount?: number;
    /**
     * Price in cents (e.g., 4999) - provide EITHER this OR price_amount
     * @type {number}
     * @memberof ProductCreate
     */
    priceMinorUnits?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    planType: ProductCreatePlanTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    billingPeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    trialDays?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreate
     */
    active?: boolean;
    /**
     * 
     * @type {object}
     * @memberof ProductCreate
     */
    metadata?: object;
}


/**
 * @export
 */
export const ProductCreatePlanTypeEnum = {
    OneTime: 'one_time',
    Monthly: 'monthly',
    Yearly: 'yearly'
} as const;
export type ProductCreatePlanTypeEnum = typeof ProductCreatePlanTypeEnum[keyof typeof ProductCreatePlanTypeEnum];


/**
 * Check if a given object implements the ProductCreate interface.
 */
export function instanceOfProductCreate(value: object): value is ProductCreate {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('planType' in value) || value['planType'] === undefined) return false;
    return true;
}

export function ProductCreateFromJSON(json: any): ProductCreate {
    return ProductCreateFromJSONTyped(json, false);
}

export function ProductCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['company_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'priceAmount': json['price_amount'] == null ? undefined : json['price_amount'],
        'priceMinorUnits': json['price_minor_units'] == null ? undefined : json['price_minor_units'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'planType': json['plan_type'],
        'billingPeriod': json['billing_period'] == null ? undefined : json['billing_period'],
        'trialDays': json['trial_days'] == null ? undefined : json['trial_days'],
        'active': json['active'] == null ? undefined : json['active'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ProductCreateToJSON(json: any): ProductCreate {
    return ProductCreateToJSONTyped(json, false);
}

export function ProductCreateToJSONTyped(value?: ProductCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company_id': value['companyId'],
        'title': value['title'],
        'description': value['description'],
        'image_url': value['imageUrl'],
        'price_amount': value['priceAmount'],
        'price_minor_units': value['priceMinorUnits'],
        'currency': value['currency'],
        'plan_type': value['planType'],
        'billing_period': value['billingPeriod'],
        'trial_days': value['trialDays'],
        'active': value['active'],
        'metadata': value['metadata'],
    };
}

