/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    priceAmount: number;
    /**
     * Price in cents (avoid floating-point errors)
     * @type {number}
     * @memberof Product
     */
    priceMinorUnits: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    planType: ProductPlanTypeEnum;
    /**
     * Billing period in days (30, 365, etc.)
     * @type {number}
     * @memberof Product
     */
    billingPeriod?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    trialDays?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Product
     */
    active?: boolean;
    /**
     * 
     * @type {object}
     * @memberof Product
     */
    metadata?: object | null;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const ProductPlanTypeEnum = {
    OneTime: 'one_time',
    Monthly: 'monthly',
    Yearly: 'yearly'
} as const;
export type ProductPlanTypeEnum = typeof ProductPlanTypeEnum[keyof typeof ProductPlanTypeEnum];


/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): value is Product {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('priceAmount' in value) || value['priceAmount'] === undefined) return false;
    if (!('priceMinorUnits' in value) || value['priceMinorUnits'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('planType' in value) || value['planType'] === undefined) return false;
    return true;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['company_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'priceAmount': json['price_amount'],
        'priceMinorUnits': json['price_minor_units'],
        'currency': json['currency'],
        'planType': json['plan_type'],
        'billingPeriod': json['billing_period'] == null ? undefined : json['billing_period'],
        'trialDays': json['trial_days'] == null ? undefined : json['trial_days'],
        'active': json['active'] == null ? undefined : json['active'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ProductToJSON(json: any): Product {
    return ProductToJSONTyped(json, false);
}

export function ProductToJSONTyped(value?: Product | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company_id': value['companyId'],
        'title': value['title'],
        'description': value['description'],
        'image_url': value['imageUrl'],
        'price_amount': value['priceAmount'],
        'price_minor_units': value['priceMinorUnits'],
        'currency': value['currency'],
        'plan_type': value['planType'],
        'billing_period': value['billingPeriod'],
        'trial_days': value['trialDays'],
        'active': value['active'],
        'metadata': value['metadata'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

