/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookUpdate
 */
export interface WebhookUpdate {
    /**
     * 
     * @type {string}
     * @memberof WebhookUpdate
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookUpdate
     */
    events?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof WebhookUpdate
     */
    apiVersion?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookUpdate
     */
    active?: boolean;
}

/**
 * Check if a given object implements the WebhookUpdate interface.
 */
export function instanceOfWebhookUpdate(value: object): value is WebhookUpdate {
    return true;
}

export function WebhookUpdateFromJSON(json: any): WebhookUpdate {
    return WebhookUpdateFromJSONTyped(json, false);
}

export function WebhookUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'events': json['events'] == null ? undefined : json['events'],
        'apiVersion': json['api_version'] == null ? undefined : json['api_version'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function WebhookUpdateToJSON(json: any): WebhookUpdate {
    return WebhookUpdateToJSONTyped(json, false);
}

export function WebhookUpdateToJSONTyped(value?: WebhookUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'events': value['events'],
        'api_version': value['apiVersion'],
        'active': value['active'],
    };
}

