/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookCount } from './WebhookCount';
import {
    WebhookCountFromJSON,
    WebhookCountFromJSONTyped,
    WebhookCountToJSON,
    WebhookCountToJSONTyped,
} from './WebhookCount';

/**
 * 
 * @export
 * @interface Webhook
 */
export interface Webhook {
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    companyId?: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Webhook
     */
    events?: Array<WebhookEventsEnum>;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    apiVersion?: string;
    /**
     * HMAC secret (masked after creation)
     * @type {string}
     * @memberof Webhook
     */
    secret?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Webhook
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Webhook
     */
    createdAt?: Date;
    /**
     * 
     * @type {WebhookCount}
     * @memberof Webhook
     */
    count?: WebhookCount;
}


/**
 * @export
 */
export const WebhookEventsEnum = {
    PaymentSucceeded: 'payment.succeeded',
    PaymentFailed: 'payment.failed',
    MembershipCreated: 'membership.created',
    MembershipUpdated: 'membership.updated',
    MembershipCanceled: 'membership.canceled',
    ProductCreated: 'product.created',
    ProductUpdated: 'product.updated',
    ProductDeleted: 'product.deleted'
} as const;
export type WebhookEventsEnum = typeof WebhookEventsEnum[keyof typeof WebhookEventsEnum];


/**
 * Check if a given object implements the Webhook interface.
 */
export function instanceOfWebhook(value: object): value is Webhook {
    return true;
}

export function WebhookFromJSON(json: any): Webhook {
    return WebhookFromJSONTyped(json, false);
}

export function WebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Webhook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'url': json['url'] == null ? undefined : json['url'],
        'events': json['events'] == null ? undefined : json['events'],
        'apiVersion': json['api_version'] == null ? undefined : json['api_version'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'active': json['active'] == null ? undefined : json['active'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'count': json['_count'] == null ? undefined : WebhookCountFromJSON(json['_count']),
    };
}

export function WebhookToJSON(json: any): Webhook {
    return WebhookToJSONTyped(json, false);
}

export function WebhookToJSONTyped(value?: Webhook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company_id': value['companyId'],
        'url': value['url'],
        'events': value['events'],
        'api_version': value['apiVersion'],
        'secret': value['secret'],
        'active': value['active'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        '_count': WebhookCountToJSON(value['count']),
    };
}

