/* tslint:disable */
/* eslint-disable */
/**
 * Whop SaaS Marketplace API
 * Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@whopsaas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookCreate
 */
export interface WebhookCreate {
    /**
     * 
     * @type {string}
     * @memberof WebhookCreate
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookCreate
     */
    url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookCreate
     */
    events: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof WebhookCreate
     */
    apiVersion?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookCreate
     */
    active?: boolean;
}

/**
 * Check if a given object implements the WebhookCreate interface.
 */
export function instanceOfWebhookCreate(value: object): value is WebhookCreate {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function WebhookCreateFromJSON(json: any): WebhookCreate {
    return WebhookCreateFromJSONTyped(json, false);
}

export function WebhookCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['company_id'],
        'url': json['url'],
        'events': json['events'],
        'apiVersion': json['api_version'] == null ? undefined : json['api_version'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function WebhookCreateToJSON(json: any): WebhookCreate {
    return WebhookCreateToJSONTyped(json, false);
}

export function WebhookCreateToJSONTyped(value?: WebhookCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company_id': value['companyId'],
        'url': value['url'],
        'events': value['events'],
        'api_version': value['apiVersion'],
        'active': value['active'],
    };
}

