# coding: utf-8

# flake8: noqa

"""
    Whop SaaS Marketplace API

    Production-grade marketplace API enabling multi-tenant SaaS, Stripe Connect payments, license management, and webhook event broadcasting.  ## Authentication All endpoints require authentication via session token cookie (`session_token`).  ## Multi-Tenancy All resources are scoped to companies. Users can access multiple companies with different roles.  ## Rate Limiting - 100 requests per minute per IP - Returns `429 Too Many Requests` when exceeded  ## Security - Tenant isolation via `company_id` filtering - Role-based access control (owner/admin/member) - Money stored in minor units (cents) to avoid floating-point errors 

    The version of the OpenAPI document: 1.0.0
    Contact: api@whopsaas.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CompaniesApi",
    "MembershipsApi",
    "ProductsApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiCompaniesGet200Response",
    "ApiCompaniesGet200ResponseCompaniesInner",
    "ApiCompaniesIdGet200Response",
    "ApiMembershipsGet200Response",
    "ApiProductsGet200Response",
    "ApiProductsIdDelete200Response",
    "ApiWebhooksGet200Response",
    "ApiWebhooksIdDelete200Response",
    "ApiWebhooksPost201Response",
    "Company",
    "CompanyCount",
    "CompanyCreate",
    "CompanyUpdate",
    "Error",
    "Membership",
    "MembershipUpdate",
    "MembershipUser",
    "Pagination",
    "Product",
    "ProductCreate",
    "ProductUpdate",
    "Webhook",
    "WebhookCount",
    "WebhookCreate",
    "WebhookUpdate",
]

# import apis into sdk package
from whopsaas.api.companies_api import CompaniesApi as CompaniesApi
from whopsaas.api.memberships_api import MembershipsApi as MembershipsApi
from whopsaas.api.products_api import ProductsApi as ProductsApi
from whopsaas.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from whopsaas.api_response import ApiResponse as ApiResponse
from whopsaas.api_client import ApiClient as ApiClient
from whopsaas.configuration import Configuration as Configuration
from whopsaas.exceptions import OpenApiException as OpenApiException
from whopsaas.exceptions import ApiTypeError as ApiTypeError
from whopsaas.exceptions import ApiValueError as ApiValueError
from whopsaas.exceptions import ApiKeyError as ApiKeyError
from whopsaas.exceptions import ApiAttributeError as ApiAttributeError
from whopsaas.exceptions import ApiException as ApiException

# import models into sdk package
from whopsaas.models.api_companies_get200_response import ApiCompaniesGet200Response as ApiCompaniesGet200Response
from whopsaas.models.api_companies_get200_response_companies_inner import ApiCompaniesGet200ResponseCompaniesInner as ApiCompaniesGet200ResponseCompaniesInner
from whopsaas.models.api_companies_id_get200_response import ApiCompaniesIdGet200Response as ApiCompaniesIdGet200Response
from whopsaas.models.api_memberships_get200_response import ApiMembershipsGet200Response as ApiMembershipsGet200Response
from whopsaas.models.api_products_get200_response import ApiProductsGet200Response as ApiProductsGet200Response
from whopsaas.models.api_products_id_delete200_response import ApiProductsIdDelete200Response as ApiProductsIdDelete200Response
from whopsaas.models.api_webhooks_get200_response import ApiWebhooksGet200Response as ApiWebhooksGet200Response
from whopsaas.models.api_webhooks_id_delete200_response import ApiWebhooksIdDelete200Response as ApiWebhooksIdDelete200Response
from whopsaas.models.api_webhooks_post201_response import ApiWebhooksPost201Response as ApiWebhooksPost201Response
from whopsaas.models.company import Company as Company
from whopsaas.models.company_count import CompanyCount as CompanyCount
from whopsaas.models.company_create import CompanyCreate as CompanyCreate
from whopsaas.models.company_update import CompanyUpdate as CompanyUpdate
from whopsaas.models.error import Error as Error
from whopsaas.models.membership import Membership as Membership
from whopsaas.models.membership_update import MembershipUpdate as MembershipUpdate
from whopsaas.models.membership_user import MembershipUser as MembershipUser
from whopsaas.models.pagination import Pagination as Pagination
from whopsaas.models.product import Product as Product
from whopsaas.models.product_create import ProductCreate as ProductCreate
from whopsaas.models.product_update import ProductUpdate as ProductUpdate
from whopsaas.models.webhook import Webhook as Webhook
from whopsaas.models.webhook_count import WebhookCount as WebhookCount
from whopsaas.models.webhook_create import WebhookCreate as WebhookCreate
from whopsaas.models.webhook_update import WebhookUpdate as WebhookUpdate

